openapi: 3.0.0
info:
  title: FLST Application API
  description: API para filtrar productos por fecha, artículo y marca.
  version: 1.0.0
paths:
  /productos:
    get:
      summary: Obtener productos
      description: Devuelve un json con el precio del producto solicitado en la fecha indicada (según los parámetros proporcionados).
      parameters:
        - name: fecha
          in: query
          description: Fecha en formato YYYY-MM-DDTHH:mm:ssZ
          schema:
            type: string
            format: date-time
        - name: articulo
          in: query
          description: ID del artículo.
          schema:
            type: integer
        - name: marca
          in: query
          description: ID de la marca.
          schema:
            type: integer
      responses:
        '200':
          description: Precio del producto en una fecha concreta devuelto correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  brand:
                    type: integer
                  requested_date:
                    type: string
                    format: date-time
                  campaign_start_date:
                    type: string
                    format: date-time
                  campaign_end_date:
                    type: string
                    format: date-time
                  price_list_order:
                    type: integer
                  priority:
                    type: integer
                  price:
                    type: float
                  currency:
                    type: string
                  backend_message:
                    type: string
        '400':
          description: Petición para obtener precio del producto en una fecha concreta errónea
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  brand:
                    type: integer
                  requested_date:
                    type: string
                    format: date-time
                  campaign_start_date:
                    type: string
                    format: date-time
                  campaign_end_date:
                    type: string
                    format: date-time
                  price_list_order:
                    type: integer
                  priority:
                    type: integer
                  price:
                    type: float
                  currency:
                    type: string
                  backend_message:
                    type: string
        '404':
          description: Petición para obtener precio del producto en una fecha concreta errónea
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  brand:
                    type: integer
                  requested_date:
                    type: string
                    format: date-time
                  campaign_start_date:
                    type: string
                    format: date-time
                  campaign_end_date:
                    type: string
                    format: date-time
                  price_list_order:
                    type: integer
                  priority:
                    type: integer
                  price:
                    type: float
                  currency:
                    type: string
                  backend_message:
                    type: string