name: Dockerize domain-application-adapter
on:
  workflow_run:
        workflows: ['Java CI with Maven']
        types: [completed]
        branches:
            - 'main'

jobs:
  
  generar-imagenes-docker:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn spring-boot:build-image