name: probar docker-compose

# FLST Do NOT distribute
# FLST NO Distribuir

on:
  workflow_run:
        workflows: ['Dockerizar domain-application-adapter']
        types: [completed]
        branches:
            - 'main'



jobs:
  compilacion:

    runs-on: ubuntu-latest

    steps:


      # Check out the repository
      - uses: actions/checkout@v4
       
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "domain"
#          test-command: "wget http://localhost:8082/actuator/health"

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "application"
#          test-command: "wget http://localhost:8081/actuator/health"

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "adapter"
#          test-command: "wget http://localhost:8080/actuator/health"